### ISSUE TITLE
上次听讲座说是要开源iOS端sdk，请问这个有这个计划吗

### ISSUE THREAD

**Issue by poholo** [upyun/ios-live-sdk#1]
上次听讲座说是要开源iOS端sdk，请问这个有这个计划吗

**Comment by roveretoa** [comment]
@poholo  现在 sdk 分为三个部分：播放器，采集器，推流器其中比较通用的部分会逐步放出来代码，现在还没有。

**Comment by poholo** [comment]
推流器其中比较通用的部分会逐步放出来代码  , 嗯 这块，现在有blog，代码开源的吗 ？
