### ISSUE TITLE
切换前后摄像头时水印的位置会变动

### ISSUE THREAD

**Issue by ghost** [upyun/ios-live-sdk#2]
切换前后摄像头时水印的位置会以屏幕中心左右翻转

**Comment by roveretoa** [comment]
@imtilp  前置摄像头采集时候，preview画面显示是需要“镜面反转”的，所以主播角度看水印也翻转了。推出的流其实是正常的，观众角度看是正常的。

后续，会改动一下：前置摄像头镜面反转变得可选；前置镜头且翻转时候，水印分两路打，专门给主播角度打个水印。

现在这部的是源码暴露的，如果你有好的实践方式，咱们也可以相互探讨一下。

**Comment by imtilp** [comment]
@rotoava 还有个偷懒的办法，不知可行否。

视频数据经过美颜处理后直接分两路走。
第一路打水印、编码、push。
第二路直接渲染到previewView上。然后将水印的UIImageView用addSubview添加到previewView上。这样就不用管是否开启镜像了。😊

**Comment by roveretoa** [comment]
@imtilp 嗯嗯，感觉你说的这个方式是最正确的。previewView 是一个本地预览和水印关联不是很强。改好后再关闭这个 issuse。

**Comment by roveretoa** [comment]
https://github.com/upyun/ios-live-sdk/commit/0a79516d75a55642a4102f79f4849bf538b931ce

改好了，previewView 不会有水印，只有推流画面有水印。如果在 previewView 想要水印效果，需要在 view 上手动贴一层。
