### ISSUE TITLE
seektotime不准

### ISSUE THREAD

**Issue by fanbaye** [upyun/ios-live-sdk#3]
播放视频时，displayPosition会从10开始；
seektotime的position给600的话，实际只会到240左右，很诡异。
例子：http://pl.youku.com/playlist/m3u8?vid=XMTc1MTM3MzEwNA%3D%3D&ts=1486397000&ctype=12&token=0504&keyframe=0&sid=048639699981012665ea0&ev=1&type=mp4&ep=ciacHEqEUMcJ7CveiD8bYSrnISYPXJZ3kkyE%2FLYfA8ZuPa%2FB6DPcqJ21Tvs%3D&oip=1998603676

**Comment by roveretoa** [comment]
@luzhenzhao 

"seektotime的position给600的话，实际只会到240左右" 这个应该是因为m3u8索引里的这个标签“#EXT-X-DISCONTINUITY”导致的。m3u8索引第一个完整mp4文件是380多秒，后面接个新的mp4时间戳重新从0开始了。
另外估计切片api也有问题，经常卡住：

`http://27.221.99.17/677567C053B3282B94AD692302/030008040057F7A8FB8BED1D1EE233F424B0E0-B140-2B59-DB25-1F522B1C03D3.mp4.ts?ts_start=0.0&ts_end=5.5&ts_seg_no=0&ts_keyframe=1&sid=048639699981012665ea0_00&sign=c03d99b4358b25490d0f9ab5c4036ee7&ctype=12`


“EXT-X-DISCONTINUITY”打断时间处理，代码需要修改一下。（safari 浏览器播放是正常的，虽然seek还是有卡顿）。

**Comment by roveretoa** [comment]
@luzhenzhao   最新的提交 https://github.com/upyun/ios-live-sdk/commit/49bae3f24fc242bd128dc5f565c7d7037ea14b22 已经把 m3u8  断层 seek （EXT-X-DISCONTINUITY） 问题改掉了。上面测试的那个 url 可以seek 准确，你可以试一下。
