### ISSUE TITLE
销毁时经常崩溃

### ISSUE THREAD

**Issue by fanbaye** [upyun/ios-live-sdk#4]
[UPStatisticsModel toJSONDictionay] 这个方法是否存在容错方面的问题
![screen shot 2017-02-07 at 1 46 57 pm](https://cloud.githubusercontent.com/assets/7568907/22679286/f08858ae-ed3b-11e6-9d21-419b4284af89.png)

**Comment by roveretoa** [comment]
@luzhenzhao  请问你用的哪个版本？最新的 v4.0.0 修改了一个这个地方的线程bug。

**Comment by fanbaye** [comment]
我用的是3.1版本，我更新一下吧
