### ISSUE TITLE
demo  闪退

### ISSUE THREAD

**Issue by winterwd** [upyun/ios-live-sdk#5]
-createDisplayFramebuffer这个方法

![image](https://cloud.githubusercontent.com/assets/14071671/24242788/d8382326-0ff3-11e7-8530-40a129de25ee.png)

**Comment by roveretoa** [comment]
@winterWD 
你好， 能否将 xcappdata/AppData/tmp/UPLiveSDKLogger 目录下的日志发一份。email: feng.ding@upai.com
