### ISSUE TITLE
推流过程设置背景音乐无效

### ISSUE THREAD

**Issue by DongHa0** [upyun/ios-live-sdk#9]
如题，在设置背景音乐之后，推流并没有背景音乐的播放

**Comment by linKnowEasy** [comment]
能否给出背景音乐的链接, 以及相关的设置代码

**Comment by DongHa0** [comment]
![image](https://user-images.githubusercontent.com/10461205/50586808-263ed700-0eb6-11e9-925c-8211384e07f0.png)
背景音乐链接(测试使用)：http://music.163.com/#/m/song?id=168091
麻烦您了

**Comment by linKnowEasy** [comment]
@DongHa0  背景音乐应该是一个 mp3 的链接地址.  类似 http://www.upyun.com/abc.mp3

您给的是网易云音乐的播放页面， 并不是一个有效的 mp3 地址

**Comment by DongHa0** [comment]
好的 我试试 谢谢了
